clouds:
  openstack:
    auth:
      auth_url: https://kvm.tacc.chameleoncloud.org:5000
      application_credential_id: "e3d984a8780b492ebc0d663ed307554a"
      application_credential_secret: "Qbplk_6_LvefYMoSKrA3AV07EGdZFzlKt0lZk1uTmMbLExvfQ2pO1b3qy_xno-LN4UJTtGZK7iF6iXs5JP2fmQ"
    region_name: "KVM@TACC"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"